In [1]:
import random
import numpy as np

In [24]:
#차원의구 
#몬테카를로 방법을 이용한 3, 4, 5차원에서 $Cn의 근사값
#2차원
def s_circle(n):
    count=0
    for i in range(n):
        x,y=random.random(), random.random()
        if x*x+y*y<1:
            count+=1
    return 4*count/n
s_circle(100)

3.12

In [25]:
#3차원
def s_circle(n):
    count=0
    for i in range(n):
        x,y,z=random.random(), random.random(), random.random()
        if x*x+y*y+z*z<1:
            count+=1
    return 8*count/n
s_circle(100)

3.68

In [28]:
#4차원
def s_circle(n):
    count=0
    for i in range(n):
        x,y,z,w=random.random(), random.random(), random.random(), random.random()
        if x*x+y*y+z*z+w*w<1:
            count+=1
    return 16*count/n
s_circle(100)

3.36

In [27]:
def s_circle(n):
    count = 0
    for i in range(n):
        x,y,z,w,t = random.random(),random.random(),random.random(),random.random(),random.random()
        if x*x+y*y+z*z+w*w+t*t<1:
            count+=1
    return 32*count/n
s_circle(100)

4.8

In [29]:
#차원구의 면적근사값
def s_circle(n,t):
    count = 0
    for i in range(n):
        rr = np.zeros(t)
        m = 0
        while(m < t):
            x = random.random()
            rr[m] = x*x
            m+=1
        print(rr,sum(rr))
        if sum(rr)<1:
            count+=1
            
    return 2**t*count/n
s_circle(100,3)

[0.22338224 0.02465354 0.04875834] 0.29679411031056974
[0.06222642 0.08289995 0.15415866] 0.299285023076696
[1.23300380e-04 8.20905489e-01 7.66981194e-03] 0.82869860170496
[0.95723665 0.37660432 0.30615387] 1.6399948322726494
[0.34239147 0.97377303 0.5494478 ] 1.865612297092842
[0.0486686  0.23423338 0.20569041] 0.4885923915443448
[4.47519457e-01 7.90232211e-01 4.86019835e-04] 1.238237687558741
[0.27739847 0.00412207 0.38057155] 0.6620920927050666
[0.01522722 0.6008649  0.57113144] 1.187223565271418
[0.01978844 0.2515848  0.7773135 ] 1.0486867355595484
[0.37944618 0.05259946 0.25170307] 0.6837487083994065
[0.63967085 0.09945192 0.02839501] 0.7675177869419174
[0.17129493 0.39508362 0.04648867] 0.6128672219819201
[0.39422016 0.00244244 0.04950799] 0.4461705907841646
[0.13662667 0.61842683 0.08645523] 0.8415087268340893
[0.04535482 0.16142192 0.08425054] 0.2910272734832008
[0.97607043 0.43207996 0.6668434 ] 2.074993783602792
[0.20902998 0.47573463 0.11387502] 0.7986396268309739
[0.8527335

4.16